apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-emoji-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-emoji-search
  template:
    metadata:
      labels:
        app: my-emoji-search
    spec:
      containers:
        - name: my-emoji-search
          # image: localhost:5000/my-emoji-search
          image: ${ORIGIN_REPO}/${REPO}:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      # restartPolicy: Always
      
---
apiVersion: v1
kind: Service
metadata:
  name: my-emoji-search
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: my-emoji-search
      # protocol: TCP
      # nodePort: 31000
  selector:
    app: my-emoji-search
